from rsf.proj import *

Program('sfdespike','Mdespike1.c')
Program('sfdespike2','Mdespike2.c')





Flow('SpringDashpot','SpringDashpot.txt','dd form=native')

Flow ('despike',['SpringDashpot','sfdespike.exe'],'./${SOURCES[1]} sigma=1.0 window=80')
 

