#!/usr/bin/env python
from rsf.proj import *

Program('sum','sum.c')

Flow   ('test1', None,
        '''
        spike nsp=1 mag=1
          n1=100 d1=1 k1=50 o1=0
          n2=90 d2=1 k2=50 o2=0  
        ''')
Flow('out1',['test1','sum.exe'],
     '''
     ./${SOURCES[1]} 
     ''')
#Result('out1',' graph')
End()
