from rsf.tex import *
import glob, os

for handout in glob.glob('handout*.tex'):
    name = os.path.splitext(handout)[0]
    Paper(name,
          lclass='cwphandout',
	use='graphicx,color,listings,amsmath,amssymb,amsbsy,hyperref,framed')
    
# ------------------------------------------------------------
for slides in glob.glob('slides*.tex'):
    slidesname = os.path.splitext(slides)[0]
    Paper(slidesname,
          lclass='cwpslides',
          use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy,comment')
    
for notes in glob.glob('notes*.tex'):
    notesname = os.path.splitext(notes)[0]
    Paper(notesname,
          lclass='cwpnotes',
          options='notesonly',
          use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy')
    
# ------------------------------------------------------------
#for article in glob.glob('article*.tex'):
#    name = os.path.splitext(article)[0]
#    Paper(name,
#          lclass='geophysics',
#          options='manuscript',
#          use='times,mathptm,natbib,color,amssymb,mathrsfs,amsbsy,lineno,ulem',
#          include=r'''
#          \linenumbers*[1]
#          ''')

for article in glob.glob('article*.tex'):
    name = os.path.splitext(article)[0]
    Paper(name,
          lclass='geophysics',
          options='manuscript',
          use='times,color,natbib,amsmath,graphicx,amssymb,amsbsy,lineno,ulem,setspace,rotating',
          include=r'''
          \linenumbers*[1]
          ''')
    
for geo in glob.glob('geo*.tex'):
    name = os.path.splitext(geo)[0]
    Paper(name,
          lclass='geophysics',
          options='twocolumn,twoside',
          use='times,natbib,amsmath,graphicx,color,amssymb,amsbsy,lineno,ulem,setspace')

for report in glob.glob('report*.tex'):
    name = os.path.splitext(report)[0]
    Paper(name,lclass='cwpreport',
          use='times,color,natbib,amsmath,amssymb,amsbsy,geometry,lineno,ulem,comment',
          include=r'''
          \setlength{\paperwidth}{8.5in}
          \setlength{\paperheight}{11.0in}
          \setlength{\topmargin}{-0.25in}
          \setlength{\textheight}{8.75in}
          \setlength{\textwidth}{6.5in}
          \setlength{\oddsidemargin}{+.015625in}
          \setlength{\evensidemargin}{+.015625in}
          ''')
    
for cover in glob.glob('cover*.tex'):
    name = os.path.splitext(cover)[0]
    Paper(name,
          lclass='geophysics',
          options='12pt',
          use='')

# ------------------------------------------------------------

for segabs in glob.glob('segabs*.tex'):
    name = os.path.splitext(segabs)[0]
    Paper(name,
          lclass='segabs',
          options='notimes',
          use='natbib,graphicx,color,listings,amsmath,amssymb,amsbsy')
    
for eageabs in glob.glob('eageabs*.tex'):
    name = os.path.splitext(eageabs)[0]
    Paper(name,
          lclass='eageabs',
          options='11pt',
          use='times,natbib,color,amssymb,amsmath,amsbsy,graphicx,fancyhdr')

for pept in glob.glob('pept*.tex'):
    name = os.path.splitext(pept)[0]
    Paper(name,
          lclass='cwppept',
          options='11pt',
          use='times,natbib,color,amssymb,amsmath,amsbsy,graphicx,fancyhdr')

for thesis in glob.glob('thesis*.tex'):
    name = os.path.splitext(thesis)[0]
    Paper(name,
        lclass='article',
#        options='letterpaper,twoside,12pt',
        options='letterpaper,12pt,nolabel',
        use='csm-thesis,natbib,amsmath,comment,listings,color,graphicx,rotating')

# End(use='color')
End(lclass='cwparticle',options='10pt',use='times,mathptm,natbib,color,amssymb,mathrsfs,amsbsy,lineno,ulem,multicol')
