from rsf.proj import *
import fdmod, adcig, encode, wemig, math
import commands

## 
 # Sigsbee 2A
##
data='sigsbee2a_stratigraphy.sgy'
Flow(['vstr2A','vstr2Ahead'],data,
         '''
         segyread tape=$SOURCE tfile=${TARGETS[1]} |
         put
         o1=0  d1=25     label1=z unit1=ft
         o2=10000 d2=25  label2=x unit2=ft
         ''',stdin=0)
# ------------------------------------------------------------
par = {
    'nt':7000, 'dt':0.001,'ot':0,    'lt':'t','ut':'s',
    'kt':100,    # wavelet delay
    'nx':3201, 'ox':0, 'dx':0.00762, 'lx':'x','ux':'km',
    'nz':1201, 'oz':0, 'dz':0.00762, 'lz':'z','uz':'km',
    'orec':16.00200, 'jrec':1, 'nrec':800,
    'osou':16.00200, 'jsou':8, 'nsou':100,
    'nb':150
    }


plotpar=par


plotpar = {
    'nt':7000, 'dt':0.001,'ot':0,    'lt':'t','ut':'s',
    'ox':16.00200, 'nx':800, 'dx':0.00762, 'lx':'x','ux':'km',
    'nz':801, 'oz':0, 'dz':0.00762, 'lz':'z','uz':'km',
    'nhz':0 , 'nhx':100, 'nhz':100, 'dht':0.001, 
    }




def dummyf(out,name):
    Flow(out,None,'\\rm /var2/ediaz/Backscatter/sigsbee/%s.rsf@; echo "success"'%name,stdin=0)










# source
par['xsou']=par['orec']+par['nrec']/2*par['dx']

par['zsou']=par['oz']
par['ixsou']=par['nx']/2
par['izsou']=1
par['jcx']=80
par['ncx']=par['nx']/par['jcx']
# add F-D modeling parameters
fdmod.param(par)
#-------------------------------------------------------------
# EIC computational domain
par['nhz']=0
par['nhx']=100
par['nhz']=par['nhx']
par['nht']=100
par['dht']=par['dt']*par['jsnap']

adcig.tparam((par['nhx']*par['dx'])/(par['nht']*par['dt']),
             2*par['nht']+1,-par['nht']*par['dt'],par['dt'],
               par['nz']   ,            par['oz'],par['dz'],
             par)

adcig.xparam(
             2*par['nhx']+1,-par['nhx']*par['dx'],par['dx'],
               par['nz']   ,            par['oz'],par['dz'],
             par)


adcig.eparam(10.0,
             2*par['nhx']+1,-par['nhx']*par['dx'],par['dx'],
             par['nhz']+1,-0.5*par['nhz']*par['dz'],par['dz'],
             par['nht']+1,-0.5*par['nht']*par['dt'],par['dt'],
             par)


# ------------------------------------------------------------
# CIGs at uniformly-sampled locations
fdmod.boxarray('gt',
               par['nz'],par['oz'],par['dz'],
               par['nrec'],par['orec'],par['dx'],
               par)
Flow('gg','gt',
     'put n2=%(nz)d n3=%(nrec)d | window j3=%(jcx)d |'%par + 
     'put n2=%d n3=1'% (par['nz']*par['nrec']/par['jcx']) )
fdmod.vertical('ggone',par['xsou'],par)
Plot('ggone',fdmod.qqplot('',par))


#-------------------------------------------------------------



par['fsou']=int((par['osou']-par['ox'])/par['dz'])
SHOTS=range(par['fsou'],
            par['fsou']+par['nsou']*par['jsou'],
            par['jsou'])



# ------------------------------------------------------------
# wavelet
Flow('wav',None,
         '''
         spike nsp=1 mag=1 n1=%(nt)d d1=%(dt)g o1=%(ot)g k1=%(kt)d |
         ricker1 frequency=15 |
         scale axis=123 |
         put label1=t label2=x label3=y |
         transp
         ''' % par)    
Result('wav',
       'transp | window n1=200 | graph title="" label1="t" label2= unit2=')
# ------------------------------------------------------------
# experiment setup
Flow('r_',None,'math n1=%(nrec)d d1=%(dx)g o1=%(orec)g output=0' % par)
Flow('r2_',None,'math n1=%(nx)d d1=%(dx)g o1=%(ox)g output=0' % par)

Flow('s_',None,'math n1=1      d1=0      o1=0      output=0' % par)
# receiver positions
Flow('zr','r_','math output="2*%(dz)g" '%par)
Flow('xr','r_','math output="x1"')
Flow('rr',['xr','zr'],
     '''
     cat axis=2 space=n
     ${SOURCES[0]} ${SOURCES[1]} | transp
     ''', stdin=0)




Flow('xr2','r2_','math output="x1"')
Flow('zr2','r2_','math output="2*%(dz)g" '%par)
Flow('rr_old',['xr2','zr2'],
     '''
     cat axis=2 space=n
     ${SOURCES[0]} ${SOURCES[1]} | transp
     ''', stdin=0)





# source positions
Flow('zs','s_','math output=.01')
Flow('xs','s_','math output=10.0')
Flow('rs','s_','math output=1')

# ------------------------------------------------------------

# Velocity
Flow('vel','vstr2A',
     '''
     scale rscale=.0003048 |
     put o1=%(oz)g d1=%(dz)g  o2=%(oz)g d2=%(dz)g 
     ''' % par)


Flow('flood_mask','vel', 	
    '''
    math output="(sign(input-4.5) +1)*0.5" |
    causint | 
    math output="input/(input+0.0000000001)"  
    ''')

Plot('vel',fdmod.cgrey('''
allpos=y bias=1.5 pclip=100 color=j title=Survey\ Design labelsz=4 titlesz=6 wheretitle=t
''',par))
Result('vel',['vel','rr','ss'],'Overlay')

# ------------------------------------------------------------

# density
Flow('den','vel','math output=1')

par['jdata']=10

par['jsnap']=10
par['snap']=10

# ------------------------------------------------------------

Flow('vel_rtm',['vel','flood_mask'],'math f2=${SOURCES[1]} output="input*(1-f2)+4.51104*f2 " ')
Flow('den_rtm','den','window ')


Flow('vel_water','vel','math output="1.5"')






iwindow='nqx=1050 oqx=%g'%(par['orec']-1.0)

par['nkx']=170
par['nlx']=par['nrec']-par['nkx']
Flow('dmask',None,
     '''
     spike nsp=1 mag=1
     n2=%(nrec)d d2=%(dx)g o2=%(orec)g k2=%(nkx)d l2=%(nlx)d
     n1=%(nt)d d1=%(dt)g o1=%(ot)g |
     smooth rect2=80 repeat=4 | 
     transp
     ''' % par)



fdmod.param(plotpar)

Plot('gg',fdmod.qqplot('',plotpar))


fdmod.point('cip0',16.00 ,4.75488,par)
fdmod.point('cip1',16.61 ,3.67284,par)
fdmod.point('cip2',17.22 ,3.16992,par)
fdmod.point('cip3',17.83 ,2.84988,par)
fdmod.point('cip4',18.44 ,2.96418,par)
fdmod.point('cip5',19.05 ,3.39852,par)
fdmod.point('cip6',19.66 ,3.60426,par)
fdmod.point('cip7',20.27 ,3.76428,par)





Flow('ggcip',['cip0','cip1','cip2','cip3','cip4','cip5','cip6','cip7'],'cat axis=2 ${SOURCES[1:8]}')

Plot('ggcip',fdmod.qqplot('plotfat=30 plotcol=6 symbol=. symbolsz=30',plotpar))
for s in SHOTS:
    stag = "-%04d"%s

    fdmod.point('ss'+stag,s*par['dx'],2*par['dz'],par)
    Plot('ss'+stag,fdmod.ssplot('plotcol=0 plotfat=20',par))

    fdmod.awefd2d('dd'+stag,'wts'+stag,'wav','vel_rtm','den_rtm','ss'+stag,'rr','jsnap=10 '+iwindow,par)

    ori=(s)*par['dx']
    par['ori']=ori

    # Here I am deleting the recorded source wavefield from the data dd-stag --> process -->ds-stag

    
    Flow('ds'+stag, ['dd'+stag],
      '''
      transp |
      mutter  x0=%(ori)g half=n  tp=1.450 t0=0.1 v0=1.45 abs=y |
      transp
      '''%par)


    # back propagation of the receiver wavefield
    wemig.bWRawe('ds'+stag,'wtr'+stag,'vel_rtm','den_rtm','rr','jsnap=10 '+iwindow,par)


    # cross-correlations: conventional image, source illumination, receiver ilumination
    # deconvolution imaging condition
 
    wemig.cic('Img'+stag,'wts'+stag,'wtr'+stag,'nbuf=100 ',par)
#    wemig.cic('sillu'+stag,'wts'+stag,'wts'+stag,'nbuf=100 ',par)
#    wemig.cic('rillu'+stag,'wtr'+stag,'wtr'+stag,'nbuf=100 ',par)

    Plot('Img'+stag,'Img'+stag,fdmod.cgrey('pclip=99.8',plotpar))

#    Flow('Img_dec'+stag,['sillu'+stag,'Img'+stag], 
#       '''
#       smooth rect1=1 rect2=1 repeat=1 |
#       math image=${SOURCES[1]} output="image/input" 
#       ''')


    # extended imaging condition:  time-lag gathers  and space-lag gathers    
    wemig.eic('cig'+stag,'wts'+stag,'wtr'+stag,'gg','nhx=0 nhz=0 ',par)
    wemig.eic('cigx'+stag,'wts'+stag,'wtr'+stag,'gg','nht=0 nhz=0 ',par)
    wemig.eic('cip'+stag,'wts'+stag,'wtr'+stag,'ggcip',' ',par)

    #delete binaries of the wavefields (scons should not know about it: 
 
    dummyf('dums'+stag,'wts'+stag)
    dummyf('dums1'+stag,'wtr'+stag)
    dummyf('dums2'+stag,'wtr'+stag+'_rev')





Flow('ss','rr','window j2=%(jsou)d'%par)
Plot('ss',fdmod.ssplot('',plotpar))
Plot('gg5','gg','window f2=%d n2=%d | '%(par['nz']*4,par['nz'])+fdmod.qqplot('',plotpar))
Plot('gg4','gg','window f2=%d n2=%d | '%(par['nz']*3,par['nz'])+fdmod.qqplot('',plotpar))
Plot('gg6','gg','window f2=%d n2=%d | '%(par['nz']*5,par['nz'])+fdmod.qqplot('',plotpar))

Plot('rr',fdmod.rrplot('',plotpar))



Flow('Image',map(lambda x:'Img-%04d'%x,SHOTS),'cat axis=3 space=n ${SOURCES[1:%d]} | stack axis=3 norm=n'%len(SHOTS))

Plot('Image','Image',fdmod.cgrey('pclip=99.',plotpar))


Plot('ccip','ggcip','window f2=5 n2=1'+fdmod.qqplot('plotfat=30 plotcol=6 symbol=. symbolsz=30',plotpar))


Result ('Image',['Image','rr','ss','gg6','ccip'],'Overlay')

Flow('Cig',map(lambda x:'cig-%04d'%x,SHOTS),
   '''
   cat axis=5 space=n ${SOURCES[1:%d]} | 
   stack axis=5 norm=n| 
   transp plane=41 |
   put n1=%d n2=%d |
   transp plane=23 |
   put d3=%g o3=%g 
   '''%(len(SHOTS),par['nz'],par['nrec']/par['jcx'],par['dx']*par['jrec']*par['jcx'],par['orec']))
   



Flow('Cigx',map(lambda x:'cigx-%04d'%x,SHOTS),
   '''
   cat axis=5 space=n ${SOURCES[1:%d]} | 
   stack axis=5 norm=n| 
   transp plane=41 |
   transp plane=23 |
   put n1=%d n2=%d |
   transp plane=23 |
   put d3=%g o3=%g 
   '''%(len(SHOTS),par['nz'],par['nrec']/par['jcx'],par['dx']*par['jrec']*par['jcx'],par['orec']))



#Result('Cig5','Cig','window n3=1 f3=4 |' + adcig.tgrey('pclip=99',plotpar))
Plot('Cig6','Cig','window n3=1 f3=5 |' + adcig.tgrey('pclip=99',plotpar))
#Result('Cigx5','Cigx','window n3=1 f3=4 |' + adcig.xgrey('pclip=99.5',plotpar))
Plot('Cigx6','Cigx','window n3=1 f3=5 |' + adcig.xgrey('pclip=99.5',plotpar))

Plot('Cig4','Cig','window n3=1 f3=3 |' + adcig.tgrey('pclip=99',plotpar))
# annotation - uses image units
Plot('t1',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (3.8,7.25,"a",-0.5,0.5))

Plot('t2',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (4.8,5.6,"b",0.,-0.7))

Plot('t3',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (3.4,4.8,"c",0.,-0.7))

Plot('t4',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (4.3,2.9,"c",-.9,1.2))


Result('Cig4','Cig4 t1 t2 t3 t4','Overlay')
Result('Cig6','Cig6 t1 t2 t3 t4','Overlay')







Plot('Cigx4','Cigx','window n3=1 f3=3 |' + adcig.xgrey('pclip=99.9',plotpar))

Plot('x1',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (3.8,7.25,"a",-0.5,0.5))

Plot('x2',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (5.0,4.5,"b",0.5,-0.5))

Plot('x3',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (3.9,4.2,"c",0.,-0.5))





Result('Cigx4','Cigx4 x1 x2 x3','Overlay')
Result('Cigx6','Cigx6 x1 x2 x3','Overlay')
 
Flow('Cip',map(lambda x:'cip-%04d'%x,SHOTS),'cat axis=5 space=n ${SOURCES[1:%d]} | stack axis=5 norm=n'%len(SHOTS))



Flow('Cip06','Cip','window f4=5 n4=1')




Plot('Cip06','window min3=-0.5 max3=0.5 |byte gainpanel=a pclip=99|'+ adcig.egrey(' frame3=50',par))


Plot('c1',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (9.6,2.8,"a",0.4,-0.5))

Plot('c2',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (9.6,1.8,"a",0.4,0.5))

Plot('c3',None,
     'box lab_fat=3 boxit=y   x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=1'%
     (4.8,5.7,"c",0.4,0.5))

Result('Cip06','Cip06 c1 c2 c3','Overlay')




End()
