from rsf.proj import *
import fdmod


par = {
'nz':121,'oz':0,'dz':25,
'nx':369,'ox':0,'dx':25

}

fdmod.param(par)

# Fetch Files from repository
raw=['marmvel.hh','marmsmooth.HH']
for file in raw:
    Fetch(file,"marm")




## Pad 250m of water velocity

Flow('mpad','marmvel.hh',
    '''
    spline o1=%(oz)g d1=%(dz)g n1=%(nz)d  | transp |
    spline o1=%(ox)g d1=%(dx)g n1=%(nx)d  | transp |
    pad beg1=10 |
    put o1=%(oz)g |
    window n1=%(nz)d 
    '''%par)

Flow('mvel','mpad','mask min=.1 |dd type=float |math v=${SOURCES[0]} output="v*(input) +(1-input)*1500"')

Result('mvel',fdmod.cgrey('color=j allpos=y ',par))

End()
