import rsf.proj

proj = rsf.proj.Project()
proj.Prepend(LIBS=['rsff90'])

proj.Program(['sdrive.f90','lbfgs.f'],
             LINK=proj.get('F90'),
             F90PATH=proj.get('CPPPATH'),
             LINKFLAGS=proj.get('F90FLAGS'))
