from rsf.proj import *
import elasticfd as fd
import elasticplot as plot
import fdutil, stiffness

par = dict(
    nx = 601, dx=0.01, ox=0,
    nz = 401, dz=0.01, oz=0,
    nt = 3601, dt = 0.001, ot = 0.0,kt=100,freq=15,
    nb = 30,srctype=2,jsnap=5
)
fdpar = fdutil.defaults(**par)

fdutil.constant2d('vp',3.0,**par)
fdutil.constant2d('vs',1.5,**par)
fdutil.constant2d('ro',1.0,**par)
fdutil.constant2d('eps',0.2,**par)
fdutil.constant2d('del',0.2,**par)
#stiffness.vti2d('cc','vp','vs','ro','eps','del',None)
stiffness.iso2d('cc','vp','vs','ro',None)

fd.windowDensity('ro-win','ro',**par) # Special for elastic

fdutil.vertical2d('rr-A_',2.0,**par)
fdutil.vertical2d('rr-B_',4.5,**par)
Flow('rr-A','rr-A_','window n2=50 j2=3')
Flow('rr-B','rr-B_','window n2=20 j2=3 f2=20')
Flow('rr','rr-A rr-B','cat axis=2 ${SOURCES[1]}')

fdutil.point2d('sou',2.0,3.0,**par)

fd.rickerdc2('wave',**par)
#plot.tensorwavelet('wave')

fd.run('data','cc','ro-win','wave','sou','rr','wfld', ani=0,**fdpar)

fdpar['srctype'] = 1
#groups = [('A',None,50),('B',50,None)]
#groups = [('A',None,25),('B',25,50),('C',50,None)]
#groups = [('A',None,25),('B',25,50),('C',50,None)]
#groups = [
#    ('A',None,12),('B',12,24),('C',24,36),('D',36,50),('E',50,60),('F',60,None)]
groups = [ ('A',None,12),('B',12,24),('C',24,36),('D',36,50)]
wflds = []
for ig in range(len(groups)):
    name,start,end = groups[ig]
    tag = name
    if not start:
        Flow('data'+tag,'data',
            '''
            window n1=%d
            ''' % end)
        Flow('rk'+tag,'rr',
            '''
            window n2=%d
            ''' % end)
    elif not end:
        Flow('data'+tag,'data',
            '''
            window f1=%d
            ''' % (start))
        Flow('rk'+tag,'rr',
            '''
            window f2=%d
            ''' % start)
    else:
        Flow('data'+tag,'data',
            '''
            window f1=%d n1=%d
            ''' % (start,end-start))
        Flow('rk'+tag,'rr',
            '''
            window f2=%d n2=%d
            ''' % (start,end-start))

    Flow('data'+tag+'-rev','data'+tag,
        '''
        reverse which=4 opt=i 
        ''')
    fd.run('junk-data'+tag,'cc','ro-win','data'+tag+'-rev',
        'rk'+tag,'rr','wfld'+tag, ani=0,**fdpar)
    Flow('wfld'+tag+'-scale','wfld'+tag,
        '''
        scale axis=1234
        ''')
    wflds.append('wfld'+tag+'-scale')
Flow('wfld-all',wflds,
    '''
    add mode=a ${SOURCES[1:-1]}
    ''')
Flow('sic',wflds,
    '''
    semblance3d thr=0.5 ${SOURCES[1:-1]}
    ''')

End()
