from rsf.proj import *
import fdmod as f
import os 

Program('gfunction','Mgfunction.c')

def odoplot(custom):
    return '''
    transp |
    dd type=complex |
    graph labelrot=n wantaxis=y title="" yreverse=y wherexlabel=t
    wantscalebar=yes symbol=. plotcol=3 plotfat=5 %s
    '''%(custom)

#Create a 25Hz sin wavelet
Flow('sin25Hz',None,
	'spike n1=41 d1=0.001 o1=0|math output="sin(2*acos(-1)*25*x1)"|pad n1=1359')

Result('sin25Hz','graph max1=0.05 min1=0')

rad=[80,1000]
m=['min1','max1']



minvals=[-3.67351e-13,-3.15976e-14]
maxvals=[4.16069e-13,3.16344e-14]





for i in range(10):
    for i2 in range(2):
        r= rad[i2];
        tag='theta%03d-r%04d'%(i*10,r)
        Flow('GF'+tag,['sin25Hz','gfunction.exe'],' ./${SOURCES[1]}  theta=%g r=%g'%(i*10,r))
        Result('odo_GF'+tag,'GF'+tag,
           odoplot('label1=u1 unit1=m label2=u3 unit2=m'+' min1=%g min2=%g max1=%g max2=%g'%(minvals[i2],minvals[i2],maxvals[i2],maxvals[i2]) ))

        Result('GF'+tag,'graph label1=time unit1=s title="\F10 q\F3 =%-5.1f, r=%5.1f" %s=0.4'%(i*10,r,m[i2-1]))



