#
from rsf.proj import *
import fdmod as f
import os 

Program('gfunction','Mgfunction.c')

def hodoplot(custom):
    return '''
    transp |
    dd type=complex |
    graph labelrot=n wantaxis=y title="" yreverse=y wherexlabel=t
    wantscalebar=yes symbol=. plotcol=3 plotfat=16 %s
    '''%(custom)

#Create a 25Hz sin wavelet
Flow('sin25Hz',None,
	'spike n1=41 d1=0.001 o1=0|math output="sin(2*acos(-1)*25*x1)"|pad n1=1359')

Result('sin25Hz','graph max1=0.05 min1=0 unit1=s label1=t title=Xo plotfat=16 ')

rad=[80,1000]
m=['min1','max1']



minvals=[-3.67351e-13,-3.15976e-14]
maxvals=[4.16069e-13,3.16344e-14]





for i2 in range(2):
    r= rad[i2];
    kptt = r/2000/0.001 
    kstt = r/1000/0.001
    lptt = kptt + 40
    lstt = kstt + 40 

    Flow('s-mask'+'%004d'%(r),None,'spike n1=1359 d1=0.001 o1=0 k1=%d l1=%d | spray axis=2 n=2 d=1 o=1'%(kstt,lstt)) 
    Flow('p-mask'+'%004d'%(r),None,'spike n1=1359 d1=0.001 o1=0 k1=%d l1=%d | spray axis=2 n=2 d=1 o=1'%(kptt,lptt))
    for i in range(10):
        tag='theta%03d-r%04d'%(i*10,r)
        Flow('GF'+tag,['sin25Hz','gfunction.exe'],' ./${SOURCES[1]}  theta=%g r=%g'%(i*10,r))
        #separate p-wave arrival time from S-wave arrivals
        Flow('s-GF'+tag,['GF'+tag,'s-mask%004d'%(r)],'math x=${SOURCES[1]} output="input*x"') 
        Flow('p-GF'+tag,['GF'+tag,'p-mask%004d'%(r)],'math x=${SOURCES[1]} output="input*x"') 
        
        Plot('hodo_s-GF'+tag,'s-GF'+tag,
           hodoplot(
           ''' 
           wantaxis=y n1tic=0 n2tic=0 label1=u1 unit1="" label2=u3 unit2=""
           min1=%g min2=%g max1=%g max2=%g  plotcol=6 dash=0 title="\F10 q\F3 =%-5.1f, R=%5.1f" yll=0.5 plotfat=16
           '''%(minvals[i2],minvals[i2],maxvals[i2],maxvals[i2],i*10,r)))
       
        Plot('hodo_p-GF'+tag,'p-GF'+tag,
           hodoplot(
           ''' 
           wantaxis=y n1tic=0 n2tic=0 label1=u1 unit1="" label2=u3 unit2=""
           min1=%g min2=%g max1=%g max2=%g plotcol=5 dash=0 title="\F10 q\F3 =%-5.1f, R=%5.1f" yll=0.5 plotfat=16
           '''%(minvals[i2],minvals[i2],maxvals[i2],maxvals[i2],i*10,r)))

        Result('hodo_p-s-GF'+tag,['hodo_p-GF'+tag,'hodo_s-GF'+tag],'Overlay')


 
        Result('hodo_GF'+tag,'GF'+tag,
           hodoplot(
           ''' 
           wantaxis=y n1tic=0 n2tic=0 label1=u1 unit1="" label2=u3 unit2=""
           min1=%g min2=%g max1=%g max2=%g   title="\F10 q\F3 =%-5.1f, R=%5.1f" yll=0.5 plotfat=16
           '''%(minvals[i2],minvals[i2],maxvals[i2],maxvals[i2],i*10,r)))
        Result('GF'+tag,'graph label1=time unit1=s title="\F10 q\F3 =%-5.1f, R=%5.1f" %s=0.4 min2=%g max2=%g plotfat=16 '%(i*10,r,m[i2-1],minvals[i2],maxvals[i2]))

End()
