from rsf.proj import *
import acousticfd as fd
import fdutil


par = dict(
nz=256,dx=10.0,ox=0.0,
nx=256,dz=10.0,oz=0.0,
ny=256,dy=10.0,oy=0.0,
nb=30,
nt=1001,dt=0.002,ot=0.0
)

fdpar = fdutil.defaults(cfl=1,fmax=30,snap=0,jsnap=1,**par)


fdutil.constant3d('vel',2000,**par)
fdutil.constant3d('alp1',0.0,**par)
fdutil.constant3d('alp2',10.0,**par)

fd.ricker('wave',**par)
#Flow('wave',None,
#    '''
#    spike
#    n1=1 n2=10 | math output="0"
#    ''')

fdutil.point3d('ss',250,250,250,**par)
fdutil.horizontal3d('rr',0.0,**par)

fd.run('data','vel','alp1','wave','ss','rr','wfld',time=True,
    binary='sfviscoawe_dev',**fdpar)

fd.run('data2','vel','alp2','wave','ss','rr','wfld2',time=True,
    binary='sfviscoawe_dev',**fdpar)

End()
